filebeat:
  inputs:
    -
      paths:
        - "/var/log/*"
      type: log
      document_type: app_laravel
      scan_frequency: 10s

output:
  logstash:
    hosts: [ "logstash:5044" ]
    index: "logs-laravel"
logging:
  files:
    rotateeverybytes: 10485760 # = 10MB
  selectors: ["*"]
  level: info

setup.kibana:
  host: "kibana:5601"
