version: "3.8"

networks:
  rede_docker:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.2/16

services:
  phpfpm:
    image: "bitnami/php-fpm:latest"
    container_name: phpfpm
    networks:
      rede_docker:
        ipv4_address: 172.31.0.5
    volumes:
      - ./../:/app
      - ./custom.ini:/opt/bitnami/php/etc/conf.d/custom.ini

  nginx:
    image: "bitnami/nginx:latest"
    container_name: nginx
    depends_on:
      - phpfpm
    networks:
      rede_docker:
        ipv4_address: 172.31.0.6
    volumes:
      - ./../:/app
      - ./server_block.conf:/opt/bitnami/nginx/conf/server_blocks/server_block.conf
    ports:
      - "8080:8080"
      - "443:443"
